# Generated by Django 4.2.23 on 2025-10-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='ASUS', max_length=100)),
                ('model_name', models.CharField(default='ROG Strix SCAR 18 G835LX-SA047W', max_length=100)),
                ('processor', models.CharField(default='Intel Core Ultra 9 275HX', max_length=255)),
                ('gpu', models.CharField(default='NVIDIA GeForce RTX 5090 Laptop GPU', max_length=255)),
                ('ram', models.PositiveIntegerField(default=64)),
                ('storage', models.PositiveIntegerField(default=4)),
                ('display_size', models.PositiveIntegerField(default=18)),
                ('display_resolution', models.CharField(default='2560 x 1600', max_length=50)),
                ('refresh_rate', models.PositiveIntegerField(default=240)),
                ('operating_system', models.CharField(default='Windows 11 Home', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
